const KEY='4472';const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-landbank-assess-key'};type Row=Record<string,any>;
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d,null,2),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function rest(base:string,service:string,path:string,opt:{method?:string,body?:unknown,prefer?:string}={}){const h:Record<string,string>={apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json'};if(opt.prefer)h.Prefer=opt.prefer;const r=await fetch(`${base}/rest/v1/${path}`,{method:opt.method||'GET',headers:h,body:opt.body==null?undefined:JSON.stringify(opt.body)});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,500)}`);return t?JSON.parse(t):null}
async function fetchJson(url:string){const r=await fetch(url,{headers:{'User-Agent':'LandBank-V2/1.0'}});const t=await r.text();if(!r.ok)throw new Error(`DataMapWales ${r.status}: ${t.slice(0,300)}`);return JSON.parse(t)}
function ringContains(lon:number,lat:number,ring:number[][]){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];const hit=((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi);if(hit)inside=!inside}return inside}
function polygonContains(lon:number,lat:number,coords:number[][][]){if(!coords?.length||!ringContains(lon,lat,coords[0]))return false;for(let i=1;i<coords.length;i++)if(ringContains(lon,lat,coords[i]))return false;return true}
function geomContains(lon:number,lat:number,g:any){if(!g)return false;if(g.type==='Polygon')return polygonContains(lon,lat,g.coordinates);if(g.type==='MultiPolygon')return g.coordinates.some((p:number[][][])=>polygonContains(lon,lat,p));return false}
const NRW=[['NRW_SSSI','sssi',30],['NRW_SAC','sac',30],['NRW_SPA','spa',30],['NRW_RAMSAR','ramsar',30],['NRW_ANCIENT_WOODLAND_INVENTORY_2021','ancient_woodland',25],['NRW_NNR','national_nature_reserve',20],['NRW_AONB','national_landscape',20],['NRW_NATIONAL_PARK','national_park',20],['NRW_LNR','local_nature_reserve',10]] as const;
function alcScore(g:string|null){const x=(g||'').trim().toLowerCase();if(x==='1')return 10;if(x==='2')return 20;if(x==='3a')return 35;if(x==='3b')return 75;if(x==='4')return 90;if(x==='5')return 100;if(x)return 60;return null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);if(req.headers.get('x-landbank-assess-key')!==KEY)return json({error:'unauthorised'},401);try{const input=await req.json();const siteId=String(input?.site_id||'');if(!siteId)return json({error:'site_id required'},400);const base=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!base||!service)throw new Error('Supabase environment unavailable');const rows=await rest(base,service,`lb_sites?id=eq.${encodeURIComponent(siteId)}&select=id,name,lat,lng,osgb_easting,osgb_northing,agricultural_score`);const s=rows?.[0];if(!s||s.lat==null||s.lng==null||s.osgb_easting==null||s.osgb_northing==null)return json({error:'site coordinates unavailable'},422);const lon=Number(s.lng),lat=Number(s.lat),e=Number(s.osgb_easting),n=Number(s.osgb_northing),d=.003;
const alcUrl=`https://datamap.gov.wales/geoserver/inspire-wg/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=inspire-wg:wg_predictive_alc2&outputFormat=json&CQL_FILTER=${encodeURIComponent(`INTERSECTS(geom,POINT(${e} ${n}))`)}&propertyName=gridcode,predictive`;
const nrwUrl=`https://datamap.gov.wales/geoserver/inspire-nrw/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=${encodeURIComponent(NRW.map(x=>`inspire-nrw:${x[0]}`).join(','))}&outputFormat=json&srsName=EPSG:4326&bbox=${lon-d},${lat-d},${lon+d},${lat+d},EPSG:4326`;
const samUrl=`https://datamap.gov.wales/geoserver/inspire-wg/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=inspire-wg:Cadw_SAM&outputFormat=json&srsName=EPSG:4326&bbox=${lon-d},${lat-d},${lon+d},${lat+d},EPSG:4326`;
const caUrl=`https://datamap.gov.wales/geoserver/geonode/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geonode:conservation_areas_wales&outputFormat=json&srsName=EPSG:4326&bbox=${lon-d},${lat-d},${lon+d},${lat+d},EPSG:4326`;
const [alc,nrw,sam,ca]=await Promise.all([fetchJson(alcUrl),fetchJson(nrwUrl),fetchJson(samUrl),fetchJson(caUrl)]);const alcFeature=alc?.features?.[0]||null;const grade=alcFeature?.properties?.predictive==null?null:String(alcFeature.properties.predictive);const isWales=Boolean(alcFeature);const hits:Row[]=[];for(const f of (nrw?.features||[])){if(!geomContains(lon,lat,f.geometry))continue;const prefix=String(f.id||'').split('.')[0];const cfg=NRW.find(x=>x[0]===prefix);if(cfg)hits.push({dataset:cfg[1],penalty:cfg[2],id:f.id,properties:f.properties||{}})}for(const f of (sam?.features||[]))if(geomContains(lon,lat,f.geometry))hits.push({dataset:'scheduled_monument',penalty:25,id:f.id,properties:f.properties||{}});for(const f of (ca?.features||[]))if(geomContains(lon,lat,f.geometry))hits.push({dataset:'conservation_area',penalty:10,id:f.id,properties:f.properties||{}});const byDataset=new Map<string,number>();for(const h of hits)byDataset.set(h.dataset,Math.max(byDataset.get(h.dataset)||0,h.penalty));const penalty=[...byDataset.values()].reduce((a,b)=>a+b,0);const pScore=isWales?Math.max(0,100-penalty):null;const aScore=alcScore(grade);const now=new Date().toISOString();const patch:Row={updated_at:now};if(isWales){patch.agricultural_grade=`Wales Predictive ${grade}`;patch.agricultural_score=aScore;patch.planning_screen_score=pScore;patch.planning_score_confidence=50;patch.planning_screened_at=now;patch.planning_evidence_class='wales_datamap_point_screen';patch.planning_constraint_count=hits.length}await rest(base,service,`lb_sites?id=eq.${siteId}`,{method:'PATCH',body:patch,prefer:'return=minimal'});if(isWales)await rest(base,service,'lb_site_assessments?on_conflict=site_id,assessment_type,provider',{method:'POST',body:[{site_id:siteId,assessment_type:'planning',score:pScore,status:'provisional_point_screen',provider:'DataMapWales / NRW / Cadw',source_ref:'DataMapWales WFS',assessed_at:now,summary:{coverage:'Wales',agricultural_grade:grade,agricultural_score:aScore,constraint_count:hits.length,datasets:Object.fromEntries(byDataset),constraints:hits,caveat:'Origination farm-pin pre-screen only; parcel-level planning and environmental due diligence remains downstream.'},raw_data:{alc:alcFeature?.properties||null}}],prefer:'resolution=merge-duplicates,return=minimal'});return json({site_id:siteId,site_name:s.name,wales_coverage:isWales,agricultural_grade:grade,agricultural_score:aScore,planning_screen_score:pScore,constraint_count:hits.length,datasets:Object.fromEntries(byDataset)})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});