import { createClient } from 'npm:@supabase/supabase-js@2';
type Row=Record<string,any>;
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
const legal=/\b(LIMITED|LTD|LLP|PLC|HOLDINGS?|COMPANY|CO)\b/g;
function canonical(s=''){return s.toUpperCase().replace(/&/g,' AND ').replace(/[^A-Z0-9 ]/g,' ').replace(legal,' ').replace(/\bAND\b/g,' ').replace(/\s+/g,' ').trim().split(' ').filter(x=>x.length>=2).join(' ')}
function toks(s=''){return canonical(s).split(' ').filter(Boolean)}
function root(domain=''){return String(domain).toLowerCase().replace(/^www\./,'').split('.')[0].replace(/[^a-z0-9]/g,'')}
function distinctive(domain='',company=''){const r=root(domain);const ts=toks(company).map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,'')).filter(x=>x.length>=3);const joined=ts.join('');return !!r&&(ts.some(t=>r.includes(t)||t.includes(r))||(joined.length>=6&&(r.includes(joined)||joined.includes(r))))}
function cleanDomain(s=''){return String(s).trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0]}
function foreignCountryDomain(d=''){const parts=cleanDomain(d).split('.');const last=parts.at(-1)||'';return last.length===2&&last!=='uk'}
function isUkDomain(d=''){return cleanDomain(d).endsWith('.uk')}
function normPc(s=''){return String(s).toUpperCase().replace(/[^A-Z0-9]/g,'')}
function normCompanyNo(s=''){return String(s).toUpperCase().replace(/[^A-Z0-9]/g,'')}
function htmlText(s=''){return s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z#0-9]+;/gi,' ').replace(/\s+/g,' ').toLowerCase()}
function admin(){const url=Deno.env.get('SUPABASE_URL');let key='';const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{key=JSON.parse(modern)?.default||''}catch{}}if(!key)key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!key)throw new Error('Missing Supabase admin credentials');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function liveVerify(domain:string,row:Row){const paths=['','/contact','/contact-us','/about','/about-us'];let combined='',resolved:string|null=null,pages=0;for(const path of paths){for(const scheme of ['https://','http://']){try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),7000);const r=await fetch(`${scheme}${domain}${path}`,{redirect:'follow',signal:ctrl.signal,headers:{'User-Agent':'LandBank contact research/1.0'}});clearTimeout(timer);if(!r.ok)continue;const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))continue;resolved=resolved||r.url;combined+=' '+htmlText((await r.text()).slice(0,400000));pages++;break}catch{}}if(combined.length>900000)break}
const compact=combined.replace(/\s/g,''),pc=normPc(row.postcode||''),cn=normCompanyNo(row.company_number||'');const lower=combined.toLowerCase(),town=String(row.town||'').trim().toLowerCase(),county=String(row.county||'').trim().toLowerCase();const postcode_hit=!!pc&&compact.toUpperCase().includes(pc),company_number_hit=!!cn&&cn.length>=5&&compact.toUpperCase().includes(cn),town_hit=town.length>=3&&lower.includes(town),county_hit=county.length>=4&&lower.includes(county),uk_signal=/\bunited kingdom\b|\bengland\b|\bscotland\b|\bwales\b|\bnorthern ireland\b|\+44\b/i.test(combined);const targetTokens=toks(row.organisation_name||'').map(x=>x.toLowerCase()),token_hits=targetTokens.filter(t=>lower.includes(t)).length;const geo_proof=postcode_hit||company_number_hit||((town_hit||county_hit)&&uk_signal);return{ok:pages>0,url:resolved,pages,postcode_hit,company_number_hit,town_hit,county_hit,uk_signal,token_hits,token_count:targetTokens.length,geo_proof}}

Deno.serve(async req=>{if(req.method!=='POST')return json({error:'POST required'},405);const supplied=req.headers.get('x-landbank-batch-key')||'';if(!supplied)return json({error:'unauthorised'},401);try{const sb=admin();const{data:valid,error:keyError}=await sb.rpc('lb_batch_key_valid',{p_key:supplied});if(keyError||!valid)return json({error:'unauthorised'},401);const key=Deno.env.get('HUNTER_API_KEY');if(!key)return json({error:'missing_hunter_key'},503);const body=await req.json().catch(()=>({})),limit=Math.max(1,Math.min(50,Math.floor(Number(body?.limit||25)))),minPriority=Math.max(0,Math.min(100,Number(body?.min_priority??80)));
const[{data:quarantine,error:q1},{data:general,error:q2}]=await Promise.all([
  sb.from('lb_domain_discovery_queue').select('*').eq('domain_source','hunter_domain_finder_quarantined').order('call_priority_score',{ascending:false}).limit(limit),
  sb.from('lb_domain_discovery_queue').select('*').is('domain_checked_at',null).gte('call_priority_score',minPriority).order('call_priority_score',{ascending:false}).limit(Math.max(limit*4,100))
]);if(q1)throw q1;if(q2)throw q2;const seen=new Set<string>(),targets:Row[]=[];for(const x of [...(quarantine||[]),...(general||[])]){if(seen.has(x.organisation_id))continue;seen.add(x.organisation_id);targets.push(x);if(targets.length>=limit)break}if(!targets.length)return json({status:'ok',selected:0,resolved:0,no_match:0,message:'No domain targets ready'});
let resolved=0,noMatch=0,crawlsQueued=0;const items:any[]=[];
for(const row of targets){const now=new Date().toISOString(),company=row.organisation_name||'',targetCanon=canonical(company),targetTokens=toks(company);const r=await fetch(`https://api.hunter.io/v2/domain-finder?company=${encodeURIComponent(company)}&limit=3&perfect_match=true&api_key=${encodeURIComponent(key)}`);if([401,403,429].includes(r.status))return json({status:'halted',http:r.status,selected:items.length,resolved,no_match:noMatch,items},r.status===429?429:502);if(!r.ok){await sb.from('lb_organisations').update({domain_checked_at:now,domain_source:`hunter_domain_finder_http_${r.status}`,domain_confidence:0,updated_at:now}).eq('id',row.organisation_id);noMatch++;items.push({organisation_id:row.organisation_id,status:'no_match',http:r.status});continue}
const b=await r.json();const candidates=(Array.isArray(b?.data)?b.data:[]).map((x:any)=>{const domain=cleanDomain(x.domain||''),candidateCanon=canonical(x.company_name||'');return{domain,company_name:x.company_name||'',email_count:x.email_count??null,canonical:candidateCanon,name_exact:!!targetCanon&&candidateCanon===targetCanon,distinctive:distinctive(domain,company),uk:isUkDomain(domain),foreign_cc:foreignCountryDomain(domain)}}).sort((a:any,b:any)=>Number(b.name_exact)-Number(a.name_exact)||Number(b.distinctive)-Number(a.distinctive)||Number(b.uk)-Number(a.uk));const best=candidates[0]||null;let live:any=null,accepted=false,rule='';if(best?.domain&&best.name_exact&&best.distinctive&&!best.foreign_cc&&targetTokens.length>=2){live=await liveVerify(best.domain,row);if(live.ok&&live.geo_proof){accepted=true;rule=best.uk?'hunter_exact_name_uk_domain_plus_live_uk_identity':'hunter_exact_name_generic_domain_plus_live_uk_identity'}}
if(accepted){const domain=best.domain;await sb.from('lb_organisations').update({domain,website:live?.url||`https://${domain}`,domain_source:rule,domain_confidence:100,domain_checked_at:now,updated_at:now}).eq('id',row.organisation_id);const{data:existing}=await sb.from('lb_web_crawl_jobs').select('id,status,url').eq('organisation_id',row.organisation_id).maybeSingle();if(!existing){await sb.from('lb_web_crawl_jobs').insert({organisation_id:row.organisation_id,opportunity_id:row.opportunity_id,site_id:row.site_id,url:live?.url||`https://${domain}`,priority_score:row.call_priority_score,status:'queued',attempts:0,updated_at:now});crawlsQueued++}else if(['failed','skipped','completed'].includes(existing.status)){await sb.from('lb_web_crawl_jobs').update({url:live?.url||`https://${domain}`,priority_score:row.call_priority_score,status:'queued',attempts:0,locked_at:null,completed_at:null,last_error:null,updated_at:now}).eq('id',existing.id);crawlsQueued++}await sb.from('lb_enrichment_events').insert({prospect_key:row.opportunity_id,organisation_id:row.organisation_id,site_id:row.site_id,provider:'hunter',enrichment_type:'domain_finder',status:'success',confidence:100,source_ref:domain,payload:{best,candidates,live,rule},created_at:now});resolved++;items.push({organisation_id:row.organisation_id,status:'resolved',domain,rule,evidence:{postcode:live.postcode_hit,company_number:live.company_number_hit,town:live.town_hit,county:live.county_hit,uk:live.uk_signal}})}else{const reason=!best?.domain?'no_candidate':best.foreign_cc?'foreign_country_domain':!best.name_exact?'name_not_exact':!best.distinctive?'domain_not_distinctive':targetTokens.length<2?'insufficient_name_tokens':!live?.ok?'website_unreachable':!live?.geo_proof?'no_uk_identity_evidence':'not_accepted';await sb.from('lb_organisations').update({domain_source:best?.domain?'hunter_domain_finder_unverified_strict':'hunter_domain_finder_no_match_strict',domain_confidence:best?.name_exact?75:0,domain_checked_at:now,updated_at:now}).eq('id',row.organisation_id);await sb.from('lb_enrichment_events').insert({prospect_key:row.opportunity_id,organisation_id:row.organisation_id,site_id:row.site_id,provider:'hunter',enrichment_type:'domain_finder',status:best?.domain?'unverified':'not_found',confidence:best?.name_exact?75:0,source_ref:best?.domain||null,payload:{best,candidates,live,rule:'not_auto_accepted',reason},created_at:now});noMatch++;items.push({organisation_id:row.organisation_id,status:best?.domain?'unverified':'no_match',candidate:best?.domain||null,reason})}}
return json({status:'ok',selected:targets.length,resolved,no_match:noMatch,crawls_queued:crawlsQueued,items})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});
