import { fromUrl } from 'npm:geotiff@2.1.3';
type Row=Record<string,any>;
const EA='https://environment.data.gov.uk/geoservices/datasets/09ea3b37-df3a-4e8b-ac69-fb0842227b04/wcs';
const EA_ID='09ea3b37-df3a-4e8b-ac69-fb0842227b04__Lidar_Composite_Elevation_DTM_2m';
const WALES='https://dmwproductionblob.blob.core.windows.net/cogs/lidar/wales_dtm_32bit_cog.tif';
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
function clamp(v:number){return Math.max(0,Math.min(100,v))}function r1(v:number){return Math.round(v*10)/10}
async function rest(base:string,service:string,path:string,opt:{method?:string,body?:unknown,prefer?:string}={}){const h:Record<string,string>={apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json'};if(opt.prefer)h.Prefer=opt.prefer;const r=await fetch(`${base}/rest/v1/${path}`,{method:opt.method||'GET',headers:h,body:opt.body==null?undefined:JSON.stringify(opt.body)});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,500)}`);return t?JSON.parse(t):null}
function q(a:number[],p:number){const s=[...a].sort((x,y)=>x-y),x=(s.length-1)*p,l=Math.floor(x),h=Math.ceil(x);return l===h?s[l]:s[l]+(s[h]-s[l])*(x-l)}
function metrics(v:number[],w:number,h:number,res:number){const good=v.filter(x=>Number.isFinite(x)&&x>-1000&&x<5000);if(good.length<100)return null;const k=Math.max(1,Math.round(10/res)),stride=Math.max(1,Math.round(6/res)),slopes:number[]=[];for(let y=k;y<h-k;y+=stride)for(let x=k;x<w-k;x+=stride){const a=v[y*w+x-k],b=v[y*w+x+k],c=v[(y-k)*w+x],d=v[(y+k)*w+x];if([a,b,c,d].some(z=>!Number.isFinite(z)||z<=-1000||z>=5000))continue;const dx=(b-a)/(2*k*res),dy=(d-c)/(2*k*res);slopes.push(Math.atan(Math.hypot(dx,dy))*180/Math.PI)}if(!slopes.length)return null;const med=q(slopes,.5),p90=q(slopes,.9),p05=q(good,.05),p95=q(good,.95),relief=p95-p05;return{score:r1(clamp(100-Math.max(0,med-3)*8-Math.max(0,p90-7)*4-Math.max(0,relief-20)*1.5)),median_slope_deg:r1(med),p90_slope_deg:r1(p90),relief_m:r1(relief),elevation_p05_m:r1(p05),elevation_p95_m:r1(p95),valid_samples:good.length,slope_samples:slopes.length}}
async function england(e:number,n:number){const half=100,url=`${EA}?service=WCS&version=2.0.1&request=GetCoverage&coverageId=${EA_ID}&subset=E(${e-half},${e+half})&subset=N(${n-half},${n+half})&format=text/plain`;const r=await fetch(url,{headers:{'User-Agent':'LandBank-V2/1.0'}}),t=await r.text();if(!r.ok)throw new Error(`EA LIDAR ${r.status}`);const m=t.match(/Grid range:\s*GridEnvelope2D\[0\.\.(\d+),\s*0\.\.(\d+)\]/),band=t.split(/Band 0:\s*/)[1];if(!m||!band)throw new Error('EA LIDAR parse failed');const w=Number(m[1])+1,h=Number(m[2])+1,v=band.trim().split(/\s+/).map(Number).slice(0,w*h),x=metrics(v,w,h,2);if(!x)throw new Error('EA LIDAR insufficient samples');return{...x,source:'Environment Agency LIDAR Composite DTM 2m',source_ref:url,resolution_m:2,confidence:80}}
async function wales(e:number,n:number){const half=100,t=await fromUrl(WALES),img=await t.getImage(),[ox,oy]=img.getOrigin(),[rx,ry]=img.getResolution(),W=img.getWidth(),H=img.getHeight();const x0=Math.max(0,Math.floor((e-half-ox)/rx)),x1=Math.min(W,Math.ceil((e+half-ox)/rx)),y0=Math.max(0,Math.floor((n+half-oy)/ry)),y1=Math.min(H,Math.ceil((n-half-oy)/ry));if(x1<=x0||y1<=y0)throw new Error('Welsh LiDAR outside raster');const raw:any=await img.readRasters({window:[x0,y0,x1,y1],interleave:true}),v=Array.from(raw as ArrayLike<number>,Number),x=metrics(v,x1-x0,y1-y0,Math.abs(rx));if(!x)throw new Error('Welsh LiDAR insufficient samples');return{...x,source:'Welsh Government national LiDAR DTM 1m',source_ref:WALES,resolution_m:Math.abs(rx),confidence:85}}
Deno.serve(async req=>{try{if(req.method!=='POST')return json({error:'POST required'},405);const input=await req.json(),siteId=String(input?.site_id||'');if(!siteId)return json({error:'site_id required'},400);const base=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!base||!service)throw new Error('Supabase environment unavailable');const rows=await rest(base,service,`lb_sites?id=eq.${encodeURIComponent(siteId)}&select=id,name,osgb_easting,osgb_northing,agricultural_grade`),s=rows?.[0];if(!s||s.osgb_easting==null||s.osgb_northing==null)return json({error:'OSGB coordinates unavailable'},422);const e=Number(s.osgb_easting),n=Number(s.osgb_northing),isWales=String(s.agricultural_grade||'').startsWith('Wales Predictive');let x:any;try{x=isWales?await wales(e,n):await england(e,n)}catch(err){if(!isWales){try{x=await wales(e,n)}catch{throw err}}else throw err}const now=new Date().toISOString();await rest(base,service,`lb_sites?id=eq.${siteId}`,{method:'PATCH',body:{topography_score:x.score,topography_median_slope_deg:x.median_slope_deg,topography_p90_slope_deg:x.p90_slope_deg,topography_relief_m:x.relief_m,topography_score_confidence:x.confidence,topography_screened_at:now,topography_evidence_class:'official_lidar_farm_pin_window',updated_at:now},prefer:'return=minimal'});await rest(base,service,'lb_site_assessments?on_conflict=site_id,assessment_type,provider',{method:'POST',body:[{site_id:siteId,assessment_type:'land',score:x.score,status:'provisional_topography_screen',provider:x.source,source_ref:x.source_ref,assessed_at:now,summary:{median_slope_deg:x.median_slope_deg,p90_slope_deg:x.p90_slope_deg,relief_m:x.relief_m,elevation_p05_m:x.elevation_p05_m,elevation_p95_m:x.elevation_p95_m,resolution_m:x.resolution_m,confidence:x.confidence,caveat:'200m terrain window around stored farm pin; origination ranking only.'},raw_data:{valid_samples:x.valid_samples,slope_samples:x.slope_samples}}],prefer:'resolution=merge-duplicates,return=minimal'});return json({site_id:siteId,site_name:s.name,...x})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});