type Row=Record<string,any>;
const UA='LandBank-Solar-Origination/2.0';
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json'}});
async function rest(base:string,key:string,path:string,opt:{method?:string,body?:unknown,prefer?:string}={}){const h:Record<string,string>={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};if(opt.prefer)h.Prefer=opt.prefer;const r=await fetch(`${base}/rest/v1/${path}`,{method:opt.method||'GET',headers:h,body:opt.body==null?undefined:JSON.stringify(opt.body)});const t=await r.text();if(!r.ok)throw new Error(`rest ${r.status}: ${t.slice(0,300)}`);return t?JSON.parse(t):null}
const legal=new Set(['limited','ltd','plc','llp','company','co','the']);
function words(s=''){return s.toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9 ]+/g,' ').split(/\s+/).filter(Boolean).filter(x=>!legal.has(x))}
function norm(s=''){return words(s).join(' ')}
function sim(a:string,b:string){const A=new Set(words(a)),B=new Set(words(b));if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size)}
function rootDomain(s=''){try{const u=/^https?:\/\//i.test(s)?new URL(s):new URL('https://'+s);return u.hostname.toLowerCase().replace(/^www\./,'')}catch{return s.toLowerCase().replace(/^www\./,'').split('/')[0]}}
function postcode(s=''){return s.toUpperCase().replace(/\s+/g,'').trim()}
function phone(s=''){let x=s.trim().replace(/^tel:/i,'').split(';')[0].replace(/[^0-9+]/g,'');if(x.startsWith('00'))x='+'+x.slice(2);if(x.startsWith('44')&&!x.startsWith('+'))x='+'+x;if(x.startsWith('0'))x='+44'+x.slice(1);return /^\+44\d{9,10}$/.test(x)?x:''}
function email(s=''){const x=s.trim().toLowerCase().replace(/^mailto:/,'');return /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(x)?x:''}
function source(el:any){const typ=el.type==='node'?'node':el.type==='way'?'way':'relation';return `https://www.openstreetmap.org/${typ}/${el.id}`}
const vRank=(s='')=>({verified:5,probable:4,catch_all:3,unknown:2,invalid:1}[s]||0);
async function save(base:string,key:string,org:string,type:string,value:string,confidence:number,url:string){if(!value)return;const existing:Row[]=await rest(base,key,`lb_contact_points?organisation_id=eq.${org}&type=eq.${type}&select=id,is_primary,confidence,verification_status`)||[];const best=existing.sort((a,b)=>(Number(b.confidence||0)+vRank(b.verification_status)*10)-(Number(a.confidence||0)+vRank(a.verification_status)*10))[0],newStrength=confidence+40,bestStrength=best?Number(best.confidence||0)+vRank(best.verification_status)*10:-1,isPrimary=!best||newStrength>bestStrength;if(isPrimary&&existing.length)await rest(base,key,`lb_contact_points?organisation_id=eq.${org}&type=eq.${type}&is_primary=eq.true`,{method:'PATCH',body:{is_primary:false},prefer:'return=minimal'});await rest(base,key,'lb_contact_points?on_conflict=organisation_id,type,value',{method:'POST',body:[{organisation_id:org,type,value,label:'OpenStreetMap public business contact',is_primary:isPrimary,verification_status:'probable',discovery_method:'osm_public_contact',provider:'openstreetmap',source_url:url,confidence,found_at:new Date().toISOString(),do_not_contact:false}],prefer:'resolution=merge-duplicates,return=minimal'})}
async function one(base:string,key:string,j:Row){const site=(await rest(base,key,`lb_sites?id=eq.${j.site_id}&select=id,name,town,postcode,lat,lng`))?.[0],org=(await rest(base,key,`lb_organisations?id=eq.${j.organisation_id}&select=id,name,website,domain`))?.[0];if(!site||!org||site.lat==null||site.lng==null)throw new Error('site/org coordinates missing');const q=`[out:json][timeout:20];(nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"phone\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"contact:phone\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"mobile\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"contact:mobile\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"email\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"contact:email\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"website\"];nwr(around:5000,${site.lat},${site.lng})[\"name\"][\"contact:website\"];) ;out center tags;`;
const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'User-Agent':UA,'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(q),signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`overpass ${r.status}`);const data=await r.json(),els:any[]=Array.isArray(data?.elements)?data.elements:[];let best:any=null,bestScore=0;const orgNorm=norm(org.name),siteNorm=norm(site.name),orgDom=rootDomain(org.domain||org.website||'');for(const el of els){const t=el.tags||{},name=String(t.name||''),nm=norm(name);let score=0;if(nm&&orgNorm&&nm===orgNorm)score=98;else if(nm&&siteNorm&&nm===siteNorm)score=94;else score=Math.max(sim(name,org.name),sim(name,site.name))*90;const pc=postcode(t['addr:postcode']||'');if(pc&&pc===postcode(site.postcode))score+=10;const web=String(t.website||t['contact:website']||'');if(orgDom&&web&&rootDomain(web)===orgDom)score=100;if(score>100)score=100;if(score>bestScore){bestScore=score;best=el}}
if(!best||bestScore<82){await rest(base,key,`lb_osm_contact_jobs?id=eq.${j.id}`,{method:'PATCH',body:{status:'no_match',locked_at:null,completed_at:new Date().toISOString(),last_result:{candidates:els.length,best_score:Math.round(bestScore)},updated_at:new Date().toISOString()},prefer:'return=minimal'});return{status:'no_match',candidates:els.length,best_score:Math.round(bestScore)}}
const t=best.tags||{},src=source(best),phones=[t.phone,t['contact:phone'],t.mobile,t['contact:mobile']].filter(Boolean).flatMap((v:any)=>String(v).split(';')).map(phone).filter(Boolean),emails=[t.email,t['contact:email']].filter(Boolean).flatMap((v:any)=>String(v).split(';')).map(email).filter(Boolean),website=String(t.website||t['contact:website']||'');let saved=0;for(const p of [...new Set(phones)].slice(0,3)){await save(base,key,j.organisation_id,p.startsWith('+447')?'mobile':'phone',p,Math.round(bestScore),src);saved++}for(const e of [...new Set(emails)].slice(0,3)){await save(base,key,j.organisation_id,'email',e,Math.round(bestScore),src);saved++}if(website){await save(base,key,j.organisation_id,'website',website,Math.round(bestScore),src);saved++;if(!org.website&&bestScore>=92)await rest(base,key,`lb_organisations?id=eq.${j.organisation_id}`,{method:'PATCH',body:{website,domain:rootDomain(website),domain_source:'openstreetmap',domain_confidence:Math.round(bestScore),domain_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},prefer:'return=minimal'})}
await rest(base,key,`lb_osm_contact_jobs?id=eq.${j.id}`,{method:'PATCH',body:{status:'completed',locked_at:null,completed_at:new Date().toISOString(),last_error:null,last_result:{candidates:els.length,best_name:t.name||null,best_score:Math.round(bestScore),saved,source:src},updated_at:new Date().toISOString()},prefer:'return=minimal'});return{status:'completed',best_name:t.name||null,best_score:Math.round(bestScore),saved}}
Deno.serve(async req=>{try{if(req.method!=='POST')return json({error:'POST required'},405);const base=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!base||!key)throw new Error('Supabase env missing');const input=await req.json().catch(()=>({})),batch=Math.max(1,Math.min(3,Number(input?.batch_size||3))),now=new Date().toISOString();const jobs:Row[]=await rest(base,key,`lb_osm_contact_jobs?status=eq.queued&attempts=lt.3&next_attempt_at=lte.${encodeURIComponent(now)}&select=*&order=priority_score.desc.nullslast&limit=${batch}`)||[];for(const j of jobs)await rest(base,key,`lb_osm_contact_jobs?id=eq.${j.id}`,{method:'PATCH',body:{status:'processing',attempts:Number(j.attempts||0)+1,locked_at:new Date().toISOString(),updated_at:new Date().toISOString()},prefer:'return=minimal'});const results=[];for(const j of jobs){try{results.push({job_id:j.id,...await one(base,key,j)})}catch(e){const msg=e instanceof Error?e.message:String(e),attempt=Number(j.attempts||0)+1,final=attempt>=3;await rest(base,key,`lb_osm_contact_jobs?id=eq.${j.id}`,{method:'PATCH',body:{status:final?'failed':'queued',locked_at:null,last_error:msg,next_attempt_at:new Date(Date.now()+attempt*10*60000).toISOString(),updated_at:new Date().toISOString()},prefer:'return=minimal'});results.push({job_id:j.id,status:final?'failed':'requeued',error:msg.slice(0,180)})}}return json({claimed:jobs.length,results})}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});