-- Append evidence-led ownership fields to the existing V2 frontend workspace.

create or replace view public.lb_frontend_workspace as
select
  o.id AS opportunity_id,
  o.legacy_company_number,
  o.name AS opportunity_name,
  o.stage,
  o.probability,
  o.sales_score,
  o.site_score,
  o.commercial_score,
  o.priority_score,
  o.estimated_25y_value,
  o.estimated_personal_25y_commission,
  o.probability_weighted_value,
  o.next_action,
  o.next_action_at,
  o.last_contacted_at,
  o.loss_reason,
  s.id AS site_id,
  s.name AS site_name,
  s.address_line,
  s.town,
  s.county,
  s.postcode,
  s.lat,
  s.lng,
  s.acreage_total,
  s.acreage_usable,
  s.parcel_count,
  s.potential_mwp,
  s.grid_score,
  s.planning_score,
  s.solar_score,
  s.land_score,
  s.environmental_score,
  s.ownership_score,
  s.overall_priority_score,
  org.id AS organisation_id,
  org.name AS organisation_name,
  org.company_number,
  org.website,
  org.domain,
  q.acres_available,
  q.usable_acres,
  q.contiguous,
  q.ownership_confirmed,
  q.occupier_or_tenant,
  q.current_land_use,
  q.access_notes,
  q.annual_consumption_kwh,
  q.annual_electricity_cost,
  q.current_tariff_p_per_kwh,
  q.mpan,
  q.half_hourly_data_available,
  q.peak_daytime_kw,
  q.three_phase_available,
  q.supply_notes,
  q.primary_objective,
  q.repayment_preference_pct,
  q.target_annual_income,
  q.decision_process,
  q.decision_makers,
  q.mortgage_or_charge,
  q.lender_name,
  q.existing_solar_or_renewables,
  q.lease_or_title_restrictions,
  q.site_visit_at,
  q.electricity_bills_received,
  q.half_hourly_data_received,
  q.letter_of_authority_received,
  q.indicative_terms_issued,
  q.heads_of_terms_issued,
  q.documents_outstanding,
  cp.phone,
  cp.phone_status,
  cp.email,
  cp.email_status,
  cp.website_contact,
  cp.contact_confidence,
  ow.ownership_status,
  ow.ccod_title_count,
  ow.inspire_point_hit_count,
  ow.resolved_spatial_title_count,
  ow.inspire_ids,
  ow.ccod_titles
from public.lb_opportunities o
join public.lb_sites s on s.id=o.site_id
left join public.lb_organisations org on org.id=o.organisation_id
left join public.lb_qualifications q on q.opportunity_id=o.id
left join lateral (
  select
    max(c.value) filter(where c.type=any(array['phone'::text,'mobile'::text]) and c.is_primary) as phone,
    max(c.verification_status) filter(where c.type=any(array['phone'::text,'mobile'::text]) and c.is_primary) as phone_status,
    max(c.value) filter(where c.type='email'::text and c.is_primary) as email,
    max(c.verification_status) filter(where c.type='email'::text and c.is_primary) as email_status,
    max(c.value) filter(where c.type='website'::text and c.is_primary) as website_contact,
    max(c.confidence) as contact_confidence
  from public.lb_contact_points c
  where c.organisation_id=org.id
) cp on true
left join public.lb_ownership_workspace ow on ow.site_id=s.id;
