create or replace view public.lb_sales_export_value as
select o.id opportunity_id,v.model_acres,v.annual_kwh_per_kwp,v.capacity_mwp_conservative,v.capacity_mwp_base,v.capacity_mwp_high_density,
       v.annual_generation_mwh_base,v.annual_gross_value_low,v.annual_gross_value_base,v.annual_gross_value_high,v.gross_25y_constant_price_base,
       v.indicative_annual_participation_pool,v.indicative_annual_personal_share,v.indicative_personal_25y_constant_price,
       v.export_price_low_gbp_mwh,v.export_price_base_gbp_mwh,v.export_price_high_gbp_mwh,v.notes
from public.lb_opportunities o left join public.lb_export_value_scenarios v on v.opportunity_id=o.id;
grant select on public.lb_sales_export_value to anon,authenticated;

create or replace view public.lb_handover_pack as
select sw.opportunity_id,sw.handover_status,sw.handover_score,sw.site_name,sw.organisation_name,sw.company_number,sw.address_line,sw.town,sw.county,sw.postcode,sw.lat,sw.lng,
       sw.decision_makers,sw.phone,sw.email,sw.preferred_contact_time,sw.authorised_decision_maker,sw.interested_in_solar_income,sw.acres_available,sw.usable_acres,sw.contiguous,sw.current_land_use,sw.occupier_or_tenant,sw.large_vehicle_access,sw.access_notes,sw.existing_solar_or_renewables,sw.mortgage_or_charge,sw.lender_name,sw.repayment_preference_pct,sw.site_visit_interest,sw.site_visit_at,sw.consent_to_share,sw.handover_notes,
       sw.site_potential_score,sw.site_potential_completeness,sw.site_potential_confidence,sw.why_calling,sw.ownership_score,sw.grid_evidence_class,sw.grid_score,sw.grid_proximity_score,sw.grid_distance_km,sw.grid_node_name,sw.generation_headroom_mw,sw.solar_score,sw.flood_zone,sw.flood_score,sw.planning_screen_score,sw.planning_constraint_count,sw.agricultural_grade,sw.agricultural_score,sw.topography_score,sw.topography_median_slope_deg,sw.topography_p90_slope_deg,sw.topography_relief_m,
       ev.capacity_mwp_conservative,ev.capacity_mwp_base,ev.capacity_mwp_high_density,ev.annual_kwh_per_kwp,ev.annual_generation_mwh_base,ev.annual_gross_value_low,ev.annual_gross_value_base,ev.annual_gross_value_high,ev.gross_25y_constant_price_base,
       jsonb_build_object(
         'opportunity',jsonb_build_object('id',sw.opportunity_id,'status',sw.handover_status,'handover_score',sw.handover_score),
         'farmer_and_company',jsonb_build_object('farm',sw.site_name,'organisation',sw.organisation_name,'company_number',sw.company_number,'decision_makers',sw.decision_makers,'phone',sw.phone,'email',sw.email,'preferred_contact_time',sw.preferred_contact_time),
         'qualification',jsonb_build_object('authorised_decision_maker',sw.authorised_decision_maker,'interested_in_solar_income',sw.interested_in_solar_income,'acres_available',sw.acres_available,'usable_acres',sw.usable_acres,'contiguous',sw.contiguous,'current_land_use',sw.current_land_use,'occupier_or_tenant',sw.occupier_or_tenant,'large_vehicle_access',sw.large_vehicle_access,'access_notes',sw.access_notes,'existing_solar_or_renewables',sw.existing_solar_or_renewables,'mortgage_or_charge',sw.mortgage_or_charge,'lender_name',sw.lender_name,'repayment_preference_pct',sw.repayment_preference_pct,'site_visit_interest',sw.site_visit_interest,'consent_to_share',sw.consent_to_share,'handover_notes',sw.handover_notes),
         'origination_evidence',jsonb_build_object('site_potential',sw.site_potential_score,'evidence_completeness',sw.site_potential_completeness,'evidence_confidence',sw.site_potential_confidence,'why_calling',sw.why_calling,'ownership_score',sw.ownership_score,'grid_class',sw.grid_evidence_class,'grid_score',sw.grid_score,'grid_proximity_score',sw.grid_proximity_score,'grid_distance_km',sw.grid_distance_km,'grid_node',sw.grid_node_name,'generation_headroom_mw',sw.generation_headroom_mw,'solar_score',sw.solar_score,'flood_zone',sw.flood_zone,'flood_score',sw.flood_score,'planning_screen_score',sw.planning_screen_score,'planning_constraint_count',sw.planning_constraint_count,'agricultural_grade',sw.agricultural_grade,'agricultural_score',sw.agricultural_score,'topography_score',sw.topography_score,'topography_median_slope_deg',sw.topography_median_slope_deg,'topography_p90_slope_deg',sw.topography_p90_slope_deg),
         'indicative_export_value',jsonb_build_object('capacity_mwp_conservative',ev.capacity_mwp_conservative,'capacity_mwp_base',ev.capacity_mwp_base,'capacity_mwp_high_density',ev.capacity_mwp_high_density,'annual_generation_mwh_base',ev.annual_generation_mwh_base,'annual_gross_value_low',ev.annual_gross_value_low,'annual_gross_value_base',ev.annual_gross_value_base,'annual_gross_value_high',ev.annual_gross_value_high,'gross_25y_constant_price_base',ev.gross_25y_constant_price_base,'caveat',ev.notes)
       ) handover_json
from public.lb_sales_workspace sw left join public.lb_sales_export_value ev on ev.opportunity_id=sw.opportunity_id;
grant select on public.lb_handover_pack to anon,authenticated;